version: '{build}'

branches:
  only:
    - master

install:
  - SET PATH=%PATH%;C:\cygwin\bin
  - gcc --version
  - gcov --version

build_script:
  - cd source\Debug
  - make
  - cd ..\..\UnitTest\Debug
  - make

test_script:
  - BitOperations_UnitTest.exe -v | tee UnitTest.log

after_test:
  - gcov src\BitOperations

artifacts:
  - path: projects\bitoperations\UnitTest\Debug\UnitTest.log
    name: UnitTest
  - path: c:\projects\bitoperations\UnitTest\Debug\UnitTest.log
    name: UnitTest_c
  - path: bitoperations/UnitTest/Debug/UnitTest.log
    name: UnitTest_forward