version: '{build}'
clone_folder: C:\projects\bitoperations

branches:
  only:
    - master

install:
  - SET PATH=%PATH%;C:\cygwin\bin
  - gcc --version
  - gcov --version

build_script:
  - cd source\Debug
  - make
  - cd ..\..\UnitTest\Debug
  - make

test_script:
  - BitOperations_UnitTest.exe -v | tee UnitTest.log

after_test:
  - gcov src\BitOperations
  - 7za log.zip *.log
  - dir %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: UnitTest\Debug\log.zip
    name: log.zip
  - path: UnitTest\Debug\UnitTest.log
    name: UnitTest.log